// Code generated by .bin/pog, do not edit manually
public static class PogpNativeVersion {
#if UNITY_EDITOR
	public const string LibName = "pogp_demo-A03E7A96-134C-43B4-B016-BB08E0FB20FF";
#else
	public const string LibName = "pogp_demo";
#endif
}
