// Code generated by .bin/pog, do not edit manually
public static class PogpNativeVersion {
#if UNITY_EDITOR
	public const string LibName = "pogp_demo-27F33042-B38F-4C9E-B195-B62713B4CF0B";
#else
	// todo: copy version automatically on build with
	// https://docs.unity3d.com/ScriptReference/Build.IPreprocessBuildWithReport.OnPreprocessBuild.html
	public const string LibName = "pogp_demo";
#endif
}
