// Code generated by .bin/pog, do not edit manually
public static class PogpNativeVersion {
#if UNITY_EDITOR
	public const string LibName = "pogp_demo-95D2E0C4-B0BF-4B3C-BB43-0F54532BACE2";
#else
	public const string LibName = "pogp_demo";
#endif
}
