#!/bin/zsh

# https://unix.stackexchange.com/questions/76505/unix-portable-way-to-get-scripts-absolute-path-in-zsh
self=${0:a}
scriptdir=${0:a:h}

case "$1" in
	test)
		(cd ts && yarn test) || exit 1
		cargo test || exit 1
		;;
	install)
		which rustup || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
		which wasm-pack || curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
		which yarn || npm install --global yarn
		(cd ts && yarn)
		;;
	dev)
		(cd rs && cargo watch -w src -s "wasm-pack build") & (cd demo && yarn dev)
		;;
	build)
		(cd rs && wasm-pack build)
		;;
	*)
		echo "Usage:"
		echo "💾 pog install - install dependencies"
		echo "🛠  pog dev     - live reload of rust and typescript"
		echo "✅ pog test    - run unit tests"
		echo "🏗  pog build   - build for deployment"
		;;
esac
