using System;
using System.Runtime.InteropServices;

// Code generated by .bin/pog, do not edit manually
// See https://blog.testdouble.com/posts/2018-07-31-complex-ffi-rust-unity-node/ for Baton idea
public static class PogpNative {
	public const string libName = PogpNativeVersion.LibName;

	[DllImport(libName)]
	public static extern int pogp_add(int a, int b);

	[DllImport(libName)]
	public static extern void pogp_start(out IntPtr baton, out GameState g);

	[DllImport(libName)]
	public static extern GameState pogp_tick(IntPtr baton, long frame, byte[] inputs, int len);

	// [DllImport(libName)]
	// public static extern void pogp_pause(IntPtr baton);

	// [DllImport(libName)]
	// public static extern void pogp_unpause(IntPtr baton);
}
