// Code generated by .bin/pog, do not edit manually
public static class PogpNativeVersion {
#if UNITY_EDITOR
	public const string LibName = "pogp_demo-1DFE33CE-1A89-4874-853D-35B0C0C3D7E4";
#else
	// todo: copy version automatically on build with
	// https://docs.unity3d.com/ScriptReference/Build.IPreprocessBuildWithReport.OnPreprocessBuild.html
	public const string LibName = "pogp_demo";
#endif
}
